In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
X=[[85,90],[80,85],[75, 80], [70, 75], [65, 70],[60, 65],[55, 60], [50, 55]]
y = [1, 1, 1, 1, 0, 0, 0, 0]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))
new_student = [[78, 82]]
prediction = knn.predict(new_student)
print("\nNew Student:")
print(new_student)
print("\nPrediction:")
if prediction[0]==1:
    print("Pass")
else:
 print("Fail")
 print("\nClassification Report:")
print(classification_report( y_test,y_pred,labels=[0, 1],target_names=["Fail", "Pass"], zero_division=0))



Confusion Matrix:
[[1 0]
 [0 1]]

Accuracy:
1.0

New Student:
[[78, 82]]

Prediction:
Pass
              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
X=np.array([[85,90],[80, 85], [75, 80],[70, 75], [65, 70], [60, 65],[55, 60],[50, 55], [45, 50],[40, 45]])
y=np.array([1,1,1,1,1,0,0,0,0,0])
model=Sequential([Dense(8,activation='relu',input_shape=(2,)),Dense(4,activation='relu'),Dense(1,activation='sigmoid')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X,y,epochs=100,verbose=0)
y_prob=model.predict(X,verbose=0)
y_pred=(y_prob>0.5).astype(int).flatten()
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))
print("\nAccuracy:")
print(accuracy_score(y, y_pred))
new_student = np.array([[78, 82]])
prediction = model.predict(new_student, verbose=0)
print("\nNew Student:")
print(new_student)
print("\nPrediction:")
if prediction[0] == 1:
    print("Pass")
else:
    print("Fail")
    print(classification_report(y,y_pred,target_names=["Fail","Pass"],zero_division=0))

Confusion Matrix:
[[0 5]
 [0 5]]

Accuracy:
0.5

New Student:
[[78 82]]

Prediction:
Fail
              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00         5
        Pass       0.50      1.00      0.67         5

    accuracy                           0.50        10
   macro avg       0.25      0.50      0.33        10
weighted avg       0.25      0.50      0.33        10



In [10]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=100, centers=2, n_features=2,random_state=0)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
model = Sequential()
model.add(Dense(12, input_dim=2,activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=0)
scores = model.evaluate(X_train, y_train, verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))


C:\Users\student\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


compile_metrics: 91.43%
